// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uvfeoz7qWuHQ5moBIZDfEBxWZE4fLr8',
    appId: '1:457982227139:web:bba5fc828bc804c3c3e876',
    messagingSenderId: '457982227139',
    projectId: 'recipies-90b32',
    authDomain: 'recipies-90b32.firebaseapp.com',
    storageBucket: 'recipies-90b32.appspot.com',
    measurementId: 'G-TMYSNPQ78L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHCDA6lIaJxAGvxJ_eb2lYBDgJ1KkZGSU',
    appId: '1:457982227139:android:5968230df938247bc3e876',
    messagingSenderId: '457982227139',
    projectId: 'recipies-90b32',
    storageBucket: 'recipies-90b32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjR7HdLN8uQqtCZ8cOAL-jrZwDnvZ8zJw',
    appId: '1:457982227139:ios:85086317c431cc0ac3e876',
    messagingSenderId: '457982227139',
    projectId: 'recipies-90b32',
    storageBucket: 'recipies-90b32.appspot.com',
    iosBundleId: 'com.example.ac7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjR7HdLN8uQqtCZ8cOAL-jrZwDnvZ8zJw',
    appId: '1:457982227139:ios:b2811967d775d146c3e876',
    messagingSenderId: '457982227139',
    projectId: 'recipies-90b32',
    storageBucket: 'recipies-90b32.appspot.com',
    iosBundleId: 'com.example.ac7.RunnerTests',
  );
}
