// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeG6hcAtRV7CZARj6VQB_UFrinPPGgpbg',
    appId: '1:794337191583:web:2f3c1ed361eb9b8b7fa4aa',
    messagingSenderId: '794337191583',
    projectId: 'recipies2-aa141',
    authDomain: 'recipies2-aa141.firebaseapp.com',
    storageBucket: 'recipies2-aa141.appspot.com',
    measurementId: 'G-G4L3285HW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsjGYFj5Das5-u6BHQg7feao8RrdAjys',
    appId: '1:794337191583:android:1381decabc3a90927fa4aa',
    messagingSenderId: '794337191583',
    projectId: 'recipies2-aa141',
    storageBucket: 'recipies2-aa141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqOioc4iUZ8WAGNZg0H5m1UrJ6u9bZAo',
    appId: '1:794337191583:ios:c658f4c565caba9d7fa4aa',
    messagingSenderId: '794337191583',
    projectId: 'recipies2-aa141',
    storageBucket: 'recipies2-aa141.appspot.com',
    iosBundleId: 'com.example.ac7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqOioc4iUZ8WAGNZg0H5m1UrJ6u9bZAo',
    appId: '1:794337191583:ios:6d1e0e8d5c099f2a7fa4aa',
    messagingSenderId: '794337191583',
    projectId: 'recipies2-aa141',
    storageBucket: 'recipies2-aa141.appspot.com',
    iosBundleId: 'com.example.ac7.RunnerTests',
  );
}
